### PR TITLE
Parse ServerVariables out of log state. #2

### PR DESCRIPTION
**Pull request by rstone770**
Adds ability to pull `ServerVariables` out of log state. This pattern should be able to be extended for other structured values like `QueryString` when needed.

I wasn't able to find out any test suites to run against so i manually tested and it works in the cases i tried.

### CODE REVIEW

**Comment by ThomasArdal** [comment]
Thanks, dude, you rock!

I have some changes in mind and want to support cookies, form values, etc. Maybe I should just base my changes on your branch and finish it off? I'll make sure to acknowledge you on the readme of course.

What do you think?

**Comment by rstone770** [comment]
Sounds good to me. I was aiming at being conservative, but it'd be really nice to have support for everything in one go.

One thing that we should be aware is handling collisions. I don't think its actually a real world scenario, but it is possible to have 2 keys like `queryString` and `QueryString` that could create non deterministic results.

I also didn't filter structured properties from state after reading them, since i didn't want to change what gets pushed into data from previous versions.

**Comment by ThomasArdal** [comment]
I think I'll just pick something simple for now. If a user specifies `queryString` and `QueryString`, it will pick the first one or something like that.

I did notice that your implementation still added server variables to `data`. I think that I'll change that. I know it's a breaking change, but the feature hasn't been available for more than a couple of months, so I think that a breaking change is ok here. Cannot imagine anyone who wants a long list of JSON serialized server variables in the data tab anyway :smile:

**Comment by rstone770** [comment]
Works for me! I thought the same thing but didn't want to make the call.
Let me know when it's been released, looking for forward to it.

**Comment by ThomasArdal** [comment]
@rstone770 Started looking into this. I see why you added the lookup for server variables before mapping everything to `Item`. I'm looking into refactoring this to only iterate over properties a single time and using extension methods to see if a property is a named field or simply an entry for `Data`:

```csharp
if (state is IEnumerable<KeyValuePair<string, object>> stateProperties)
{
    foreach (var stateProperty in stateProperties.Where(prop => prop.Key != OriginalFormatPropertyKey))
    {
        if (stateProperty.IsStatusCode(out int? statusCode)) createMessage.StatusCode = statusCode.Value;
        else if (stateProperty.IsApplication(out string application)) createMessage.Application = application;
        else if (stateProperty.IsSource(out string source)) createMessage.Source = source;
        ...
        else if (stateProperty.IsServerVariables(out List<Item> serverVariables)) createMessage.ServerVariables = serverVariables;
        else if (stateProperty.IsCookies(out List<Item> cookies)) createMessage.Cookies = cookies;
        else createMessage.Data.Add(ToItem(stateProperty));
    }
}
```

What do you think about this approach?

**Comment by ThomasArdal** [comment]
Nevermind. Here is the "finished" code:

```csharp
if (state is IEnumerable<KeyValuePair<string, object>> stateProperties)
{
    // Fill in fields by looking at properties provided by MEL.
    // Properties than we cannot map to elmah.io fields, are added to the Data tab.
    foreach (var stateProperty in stateProperties.Where(prop => prop.Key != OriginalFormatPropertyKey))
    {
        if (stateProperty.IsStatusCode(out int? statusCode)) createMessage.StatusCode = statusCode.Value;
        else if (stateProperty.IsApplication(out string application)) createMessage.Application = application;
        else if (stateProperty.IsSource(out string source)) createMessage.Source = source;
        else if (stateProperty.IsHostname(out string hostname)) createMessage.Hostname = hostname;
        else if (stateProperty.IsUser(out string user)) createMessage.User = user;
        else if (stateProperty.IsMethod(out string method)) createMessage.Method = method;
        else if (stateProperty.IsVersion(out string version)) createMessage.Version = version;
        else if (stateProperty.IsUrl(out string url)) createMessage.Url = url;
        else if (stateProperty.IsType(out string type)) createMessage.Type = type;
        else if (stateProperty.IsServerVariables(out List<Item> serverVariables)) createMessage.ServerVariables = serverVariables;
        else if (stateProperty.IsCookies(out List<Item> cookies)) createMessage.Cookies = cookies;
        else if (stateProperty.IsForm(out List<Item> form)) createMessage.Form = form;
        else if (stateProperty.IsQueryString(out List<Item> queryString)) createMessage.QueryString = queryString;
        else createMessage.Data.Add(stateProperty.ToItem());
    }
}

// Fill in as many blanks as we can by looking at environment variables, etc.
if (string.IsNullOrWhiteSpace(createMessage.Source)) createMessage.Source = Source(exception);
if (string.IsNullOrWhiteSpace(createMessage.Hostname)) createMessage.Hostname = Hostname();
if (string.IsNullOrWhiteSpace(createMessage.User)) createMessage.User = User();
if (string.IsNullOrWhiteSpace(createMessage.Type)) createMessage.Type = Type(exception);

if (exception != null)
{
    createMessage.Detail = exception?.ToString();
    foreach (var item in exception.ToDataList())
    {
        createMessage.Data.Add(item);
    }
}
```

I'm interested in hearing how you tested your code. No matter what I do, Microsoft.Extensions.Logging tostring my objects:

```csharp
var form = new List<KeyValuePair<string, object>> { new KeyValuePair<string, object>("Form-Key", "Form-Value") };
logger.LogInformation("A message with {form}", form);
```

doesn't trigger the if check in `ToItemList`, since `property.Value` is of type `string` rather than `IEnumerable<KeyValuePair<string, object>>`.

**Comment by rstone770** [comment]
For testing, I replaced the nuget package with a reference to the local built assembly in the project I was using the logger in. I was testing using `Log<TState>` not `LogInformation` which i think is where issue is.

Ill follow up once I look at what LogInformation is doing.

**Comment by rstone770** [comment]
Ok so it looks like what happens is when you use any of the `LoggerExtensions` methods, calls get filtered through into a `Log` [call](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L389) that [formats](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs#L69) all values. But it seems to expose an '{OriginalFormat}' key which contains the original unformated value.

We may have to do something like try populate from `{OriginalFormat}` else `state` like we are currently doing.

**Comment by rstone770** [comment]
Im an idiot, `{OriginalFormat}` is the original message not the values. Sorry.

**Comment by ThomasArdal** [comment]
Well, that makes sense, since `statusCode` is also tostring'ed. I parse that like this:

```csharp
internal static bool IsStatusCode(this KeyValuePair<string, object> keyValue, out int? statusCode)
{
    statusCode = null;
    if (!keyValue.Is("statuscode")) return false;
    if (keyValue.Value == null || string.IsNullOrWhiteSpace(keyValue.Value.ToString())) return false;
    if (!int.TryParse(keyValue.Value.ToString(), out int code)) return false;
    statusCode = code;
    return true;
}
```

So, `serverVariables` isn't really different, besides it needs a more complex parser. I'll look into how that can be done. I think a nice benefit of this is, that anything that can be parsed as an enumerable of key values, can go into `serverVariables` and not necessarily need to be of type `IEnumerable<KeyValuePair<string, object>>`.

Thank you for looking into this!

**Comment by ThomasArdal** [comment]
Damn. Been digging deep into Microsoft.Extensions.Logging tonight. Need to go watch The Wire to cool down now 😃

This is where the magic happens: https://github.com/aspnet/Extensions/blob/2.2.0/src/Logging/Logging.Abstractions/src/Internal/LogValuesFormatter.cs#L140. MEL converts any `IEnumerable` to a comma-separated list. In the example of a `KeyValuePair`, this will output `[key, value], [key2, value2]`.

Will figure out how to parse this in a good way.

**Comment by ThomasArdal** [comment]
@rstone770 Uuuuuuuuh!

image

**Comment by ThomasArdal** [comment]
I think I'll publish this as a prerelease. Would you like to try it out on a real website?

**Comment by rstone770** [comment]
Yeah ill take a look! Thanks for taking care of this. It's pretty crazy how inflexible the standard logging infra is.

**Comment by ThomasArdal** [comment]
Great. The new version is available here: https://www.nuget.org/packages/Elmah.Io.Extensions.Logging/3.4.37-pre

**Comment by ThomasArdal** [comment]
Hey @rstone770. Did you get around to look at the new prerelease? If everything is working as expected, I'll release a stable version for others to enjoy :smile:

**Comment by rstone770** [comment]
Im sorry I haven't been able to test just yet due to some urgent work
demands. But im planning on testing in the next day or two. I will let you
know.

**Pull request merged**
